import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { processedImage, bgColor, options } = body;

    if (!processedImage) {
      return NextResponse.json({ error: 'No processed image provided' }, { status: 400 });
    }

    const copies = options?.copies || 4;
    const country = options?.country || 'india';
    const backgroundColor = bgColor || '#FFFFFF';
    const cols = copies <= 4 ? 2 : 4;
    const rows = Math.ceil(copies / cols);

    // Country-specific dimensions at 300dpi
    const dimensions: Record<string, { w: number; h: number; label: string }> = {
      india:     { w: 413,  h: 531,  label: 'India 35×45mm' },
      usa:       { w: 600,  h: 600,  label: 'USA 2×2 inch' },
      uk:        { w: 413,  h: 531,  label: 'UK 35×45mm' },
      canada:    { w: 591,  h: 827,  label: 'Canada 50×70mm' },
      australia: { w: 413,  h: 531,  label: 'Australia 35×45mm' },
      schengen:  { w: 413,  h: 531,  label: 'Schengen 35×45mm' },
    };

    const dim = dimensions[country] || dimensions.india;
    const gap = 12;
    const padding = 24;

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Passport Photos — ${dim.label}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    background: #f5f5f5;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    font-family: Arial, sans-serif;
    padding: 20px;
  }
  h1 {
    font-size: 14px;
    color: #333;
    margin-bottom: 12px;
    text-align: center;
  }
  .sheet {
    display: grid;
    grid-template-columns: repeat(${cols}, ${dim.w}px);
    gap: ${gap}px;
    padding: ${padding}px;
    background: white;
    border: 1px solid #ddd;
    box-shadow: 0 4px 20px rgba(0,0,0,0.1);
    border-radius: 8px;
  }
  .photo {
    width: ${dim.w}px;
    height: ${dim.h}px;
    overflow: hidden;
    border: 1px solid #bbb;
    background-color: ${backgroundColor};
    position: relative;
  }
  .photo img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center top;
  }
  .info {
    margin-top: 12px;
    font-size: 11px;
    color: #666;
    text-align: center;
  }
  @media print {
    body { background: white; padding: 0; }
    .info { display: none; }
  }
</style>
</head>
<body>
<h1>Passport Photo Sheet — ${dim.label} — ${copies} copies</h1>
<div class="sheet">
${Array(copies).fill(null).map(() => `  <div class="photo"><img src="${processedImage}" alt="passport photo" /></div>`).join('\n')}
</div>
<div class="info">Print at 300 DPI for correct size &nbsp;|&nbsp; Cut along borders &nbsp;|&nbsp; Generated by SnapID AI</div>
</body>
</html>`;

    return NextResponse.json({
      success: true,
      sheetHtml: html,
      meta: { copies, cols, rows, country: dim.label, bgColor: backgroundColor },
    });

  } catch (error: any) {
    console.error('Sheet generation error:', error);
    return NextResponse.json({ error: error.message || 'Sheet generation failed' }, { status: 500 });
  }
}